#!/bin/sh
# Creates a link to all header files (i.e. files 
# named *.h) under the current directory. Duplicated
# header files will appear in include/make_includes.err

mkdir -p include
cd include
rm -f `ls *.h|grep -v vehicle_common`
rm -f make_includes.err
FILELIST=`find .. -name "*.h" | grep -v Leddar`
cp $FILELIST . 2>make_includes.err
