/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_PATH_BSM.ASN"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_EgoFlags_H_
#define	_EgoFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EgoFlags */
typedef OCTET_STRING_t	 EgoFlags_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EgoFlags_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EgoFlags;
asn_struct_free_f EgoFlags_free;
asn_struct_print_f EgoFlags_print;
asn_constr_check_f EgoFlags_constraint;
ber_type_decoder_f EgoFlags_decode_ber;
der_type_encoder_f EgoFlags_encode_der;
xer_type_decoder_f EgoFlags_decode_xer;
xer_type_encoder_f EgoFlags_encode_xer;
oer_type_decoder_f EgoFlags_decode_oer;
oer_type_encoder_f EgoFlags_encode_oer;
per_type_decoder_f EgoFlags_decode_uper;
per_type_encoder_f EgoFlags_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EgoFlags_H_ */
#include <asn_internal.h>
