
# Makefile - PATH GPS sample programs
#
# Copyright (c) 2008   Regents of the University of California
#

include $(CAPATH_MK_DEFS)

PATH_INCLUDES = pixell.h
PATH_CFLAGS += -I../../../steinhoff -I../../../include -fPIC

EXEC = $(OBJDIR)/clt_vars_pixell $(OBJDIR)/pixell

all: $(OBJDIR) $(PATH_INCLUDES) $(PATH_OBJS) $(EXEC)

$(OBJDIR):
	mkdir -p $(OBJDIR)

clean:
	rm -f $(OBJDIR)/*.o *.err $(EXEC)
