/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_PATH_BSM.ASN"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_CaccData_H_
#define	_CaccData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CACCFlags.h"
#include "EgoFlags.h"
#include "Velocity.h"
#include "ThrottlePosition.h"
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include "DDateTime.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CaccData */
typedef struct CaccData {
	CACCFlags_t	 caccFlags;
	EgoFlags_t	 egoFlags;
	Velocity_t	 setSpeed;
	ThrottlePosition_t	 throtPos;
	long	 grpID;
	long	 grpSize;
	long	 grpMode;
	long	 grpManDes;
	long	 grpManID;
	OCTET_STRING_t	 vehID;
	long	 frntCutIn;
	long	 vehGrpPos;
	long	 vehFltMode;
	long	 vehManDes;
	long	 vehManID;
	long	 distToPVeh;
	long	 relSpdPVeh;
	long	 disToLVeh;
	long	 relSpdLVeh;
	long	 desTGapPVeh;
	long	 desTGapLVeh;
	long	 estDisPVeh;
	long	 estDisLVeh;
	long	 desSpd;
	long	 desTrq;
	long	 desAcc;
	long	 userDI1;
	long	 userDI2;
	long	 userDF1;
	long	 userDF2;
	long	 userDF3;
	DDateTime_t	 utcTime;
	long	 globalTime;
	BOOLEAN_t	 userBit1;
	BOOLEAN_t	 userBit2;
	BOOLEAN_t	 userBit3;
	BOOLEAN_t	 userBit4;
	BOOLEAN_t	 laneDepartWarnRt;
	BOOLEAN_t	 laneDepartWarnLt;
	long	 handShake;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CaccData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CaccData;
extern asn_SEQUENCE_specifics_t asn_SPC_CaccData_specs_1;
extern asn_TYPE_member_t asn_MBR_CaccData_1[40];

#ifdef __cplusplus
}
#endif

#endif	/* _CaccData_H_ */
#include <asn_internal.h>
