/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_PATH_BSM.ASN"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_CACCFlags_H_
#define	_CACCFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CACCFlags */
typedef OCTET_STRING_t	 CACCFlags_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CACCFlags_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CACCFlags;
asn_struct_free_f CACCFlags_free;
asn_struct_print_f CACCFlags_print;
asn_constr_check_f CACCFlags_constraint;
ber_type_decoder_f CACCFlags_decode_ber;
der_type_encoder_f CACCFlags_encode_der;
xer_type_decoder_f CACCFlags_decode_xer;
xer_type_encoder_f CACCFlags_encode_xer;
oer_type_decoder_f CACCFlags_decode_oer;
oer_type_encoder_f CACCFlags_encode_oer;
per_type_decoder_f CACCFlags_decode_uper;
per_type_encoder_f CACCFlags_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CACCFlags_H_ */
#include <asn_internal.h>
