/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_PATH_BSM.ASN"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_CaccData_H_
#define	_CaccData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CACCFlags.h"
#include "Velocity.h"
#include "ThrottlePosition.h"
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DDateTime;

/* CaccData */
typedef struct CaccData {
	CACCFlags_t	*flags	/* OPTIONAL */;
	Velocity_t	*setSpeed	/* OPTIONAL */;
	ThrottlePosition_t	*throtPos	/* OPTIONAL */;
	OCTET_STRING_t	*lclPN	/* OPTIONAL */;
	OCTET_STRING_t	*lclPE	/* OPTIONAL */;
	OCTET_STRING_t	*lclPD	/* OPTIONAL */;
	OCTET_STRING_t	*roll	/* OPTIONAL */;
	OCTET_STRING_t	*pitch	/* OPTIONAL */;
	OCTET_STRING_t	*yaw	/* OPTIONAL */;
	OCTET_STRING_t	*hPosAcry	/* OPTIONAL */;
	OCTET_STRING_t	*vPosAcry	/* OPTIONAL */;
	OCTET_STRING_t	*fwrdVel	/* OPTIONAL */;
	OCTET_STRING_t	*rightVel	/* OPTIONAL */;
	OCTET_STRING_t	*downVel	/* OPTIONAL */;
	OCTET_STRING_t	*velAcc	/* OPTIONAL */;
	OCTET_STRING_t	*fwrdAcc	/* OPTIONAL */;
	OCTET_STRING_t	*rightAcc	/* OPTIONAL */;
	OCTET_STRING_t	*dwnAcc	/* OPTIONAL */;
	long	*grpID	/* OPTIONAL */;
	long	*grpSize	/* OPTIONAL */;
	long	*grpMode	/* OPTIONAL */;
	long	*grpManDes	/* OPTIONAL */;
	long	*grpManID	/* OPTIONAL */;
	OCTET_STRING_t	*vehID	/* OPTIONAL */;
	long	*frntCutIn	/* OPTIONAL */;
	long	*vehGrpPos	/* OPTIONAL */;
	long	*vehFltMode	/* OPTIONAL */;
	long	*vehManDes	/* OPTIONAL */;
	long	*vehManID	/* OPTIONAL */;
	long	*distToPVeh	/* OPTIONAL */;
	long	*relSpdPVeh	/* OPTIONAL */;
	long	*disToLVeh	/* OPTIONAL */;
	long	*relSpdLVeh	/* OPTIONAL */;
	long	*desTGapPVeh	/* OPTIONAL */;
	long	*desTGapLVeh	/* OPTIONAL */;
	long	*estDisPVeh	/* OPTIONAL */;
	long	*estDisLVeh	/* OPTIONAL */;
	long	*desSpd	/* OPTIONAL */;
	long	*desTrq	/* OPTIONAL */;
	long	*desAcc	/* OPTIONAL */;
	long	*userDI1	/* OPTIONAL */;
	long	*userDI2	/* OPTIONAL */;
	long	*userDF1	/* OPTIONAL */;
	long	*userDF2	/* OPTIONAL */;
	long	*userDF3	/* OPTIONAL */;
	struct DDateTime	*utcTime	/* OPTIONAL */;
	long	*globalTime	/* OPTIONAL */;
	BOOLEAN_t	*userBit1	/* OPTIONAL */;
	BOOLEAN_t	*userBit2	/* OPTIONAL */;
	BOOLEAN_t	*userBit3	/* OPTIONAL */;
	BOOLEAN_t	*userBit4	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CaccData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CaccData;
extern asn_SEQUENCE_specifics_t asn_SPC_CaccData_specs_1;
extern asn_TYPE_member_t asn_MBR_CaccData_1[51];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DDateTime.h"

#endif	/* _CaccData_H_ */
#include <asn_internal.h>
